services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: banana
      POSTGRES_DB: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always
  postgrest:
    image: postgrest/postgrest
    environment:
      PGRST_DB_URI: postgres://postgres:banana@database:5432/postgres
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: postgres
      PGRST_SERVER_PORT: 3000
    depends_on:
      - database
    restart: always
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: test@email.de
      PGADMIN_DEFAULT_PASSWORD: banana
    ports:
      - "8090:80"
    depends_on:
      - database
    restart: always
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./assetbundles:/usr/share/nginx/assetbundles
    depends_on:
      - postgrest
    restart: always
